# Generated by Django 4.2.6 on 2024-01-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Wishlists',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='scrapboxapp.scrap'),
        ),
    ]
